<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Assessment extends Model
{
    protected $table = 'assessments';
    protected $fillable = [
        'patient_Id',
        'conductor',
        'date',
        'time',
        'orientation_level',
        'person',
        'place',
        'situation',
        'temperature',
        'blood_pressure',
        'respiratory_rate',
        'pulse_rate',
        'oxygen_saturation',
        'hair',
        'eyes',
        'perrla',
        'nose',
        'ears',
        'mouth',
        'midline_tongue',
        'moist',
        'lesions',
        'dentition',
        'carotid_pulse',
        'jugular_vein_distention',
        'trachea_midline',
        'muffled',
        'arrhythmia',
        'anterior',
        'posterior',
        'lateral',
        'chest_symmetry',
        'skin_turgor',
        'inspection',
        'palpation',
        'auscultation',
        'luq',
        'ruq',
        'llq',
        'rlq',
        'radial_pulses',
        'radial_other',
        'temperaturetrunk',
        'grip',
        'capillary_refill',
        'hair_present',
        'edema',
        'foot_strength',
        'yellowed',
        'thickened',
        'ingrown',
        'upper_r1',
        'upper_r2',
        'upper_l1',
        'upper_l2',
        'lower_r1',
        'lower_r2',
        'lower_l1',
        'lower_l2',
        'sensation',
        'weight',
        'height',
        'bmi',
        'type',
        'intensity',
        'location',
        'duration',
        'characteristics',
        'precipitation',
        'frequency',
        'nonverbals',
        'relief_factors',
        'sleep',
        'description',
        'created_at',
        'updated_at'
    ];
}
